# Generated by Django 4.1 on 2022-08-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_carmodel_imgpng'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carcateg', to='main.category'),
        ),
    ]
