# Generated by Django 4.1 on 2022-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_newcategory_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(related_name='carcateg1', to='main.newcategory'),
        ),
    ]
