# Generated by Django 4.1 on 2022-09-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_car_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
