# Generated by Django 4.1 on 2022-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_carmodel_category_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=30, verbose_name='Customer_services title')),
                ('about', models.TextField(verbose_name='Customer_services about')),
            ],
            options={
                'verbose_name': 'Customer_services',
                'verbose_name_plural': 'Customer_services',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
