# Generated by Django 4.1 on 2022-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_tilte_customer_services_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_second_column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Services_second_column image')),
                ('title', models.CharField(max_length=30, verbose_name='Services_second_column title')),
                ('columnurl', models.URLField(verbose_name='Services_second_column url')),
                ('about', models.TextField(verbose_name='Detals')),
            ],
            options={
                'verbose_name': 'Services_second_column',
                'verbose_name_plural': 'Services_second_columns',
            },
        ),
    ]
