# Generated by Django 4.1 on 2022-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_services_second_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_second_column',
            name='text',
            field=models.TextField(default=1, verbose_name='Services_second_column text'),
            preserve_default=False,
        ),
    ]
