# Generated by Django 4.1 on 2022-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_galleryphoto_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleryphotoabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Galleryphotoabout image')),
                ('title', models.CharField(max_length=30, verbose_name='Galleryphotoabout title')),
                ('about', models.TextField(verbose_name='Galleryphotoabout about')),
                ('galleryphotoabout', models.ManyToManyField(related_name='photoabout', to='main.galleryphoto')),
            ],
            options={
                'verbose_name': 'Galleryphotoabout',
                'verbose_name_plural': 'Galleryphotoabout',
            },
        ),
    ]
