# Generated by Django 4.1 on 2022-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_galleryphotoabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='about',
            field=models.TextField(default=1, verbose_name='Galleryphotoabout about'),
            preserve_default=False,
        ),
    ]
