# Generated by Django 4.1 on 2022-09-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_galleryphoto_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galleryphotoabout',
        ),
    ]
