# Generated by Django 4.1 on 2022-09-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_galleryphotoabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='imgpng',
        ),
    ]
