# Generated by Django 4.1 on 2022-09-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_galleryphoto_imgpng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='imgpng',
        ),
    ]
