# Generated by Django 4.1 on 2022-09-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_car_imgpng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcategory',
            name='image',
        ),
    ]
