# Generated by Django 4.1 on 2022-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_newcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Googlemaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Galleryphoto title')),
            ],
        ),
    ]
