# Generated by Django 4.1 on 2022-09-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_aboutus2_remove_aboutus_urlabout_aboutus_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus2',
            name='urlabout',
        ),
    ]
